---
title: "Dashboard Tingkat Kemiskinan Jateng (Berdasarkan Kabupaten)"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    theme: lumen
    source_code: embed
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(openxlsx)
library(shiny)
library(leaflet)
library(highcharter)
library(dplyr)
library(crosstalk)
library(DT)
library(d3scatter)
library(scales)


hasil <- read.xlsx("data_kemiskinan_jateng.xlsx")
hasil3 <- read.xlsx("data_jateng.xlsx")
hasil5 <- read.xlsx("persentase_jateng.xlsx")
label <- read.xlsx("data_label.xlsx")
jateng <- read.xlsx("jateng.xlsx")
lokasi_gis <- read.xlsx("lokasi.xlsx")

lokasi_gis <- (merge(lokasi_gis, label, by = 'kabupaten'))


getColor <- function(jateng) {
  sapply(jateng$Rasio_Penduduk_Miskin, function(Rasio_Penduduk_Miskin) {
  if(Rasio_Penduduk_Miskin > 0.1703) {
    "orange"
  } else if(Rasio_Penduduk_Miskin > 0.1256 & Rasio_Penduduk_Miskin <= 0.1703) {
    "blue"
  } else {
    "green"
  } })
}

icons <- awesomeIcons(
  icon = 'ios-close',
  iconColor = 'black',
  library = 'ion',
  markerColor = getColor(jateng)
) 



getColor2 <- function(lokasi_gis) {
  sapply(lokasi_gis$Rasio, function(Rasio) {
  if(Rasio > 0.1703) {
    "orange"
  } else if(Rasio > 0.1256 & Rasio <= 0.1703) {
    "blue"
  } else {
    "green"
  } })
}

icons2 <- awesomeIcons(
  icon = 'ios-close',
  iconColor = 'black',
  library = 'ion',
  markerColor = getColor2(lokasi_gis)
)  


sd <- SharedData$new(jateng)
sd_df <- SharedData$new(as.data.frame(jateng), group = sd$groupName())

#https://dgatbig.shinyapps.io/flex_dashboard_jateng_awal/

#Dashboard Monitor Kesejahteraan Masyarakat Kabupaten Jateng

```

Indikator Kemiskinan
=======================================================================

Inputs {.sidebar}
-----------------------------------------------------------------------

---

**Penjelasan:**   
Dashboard ini ditujukan untuk memantau tingkat kesejahteraan pada seluruh Kabupaten di Propinsi Jawa Tengah tahun 2012 - 2016.Dashboard ini memiliki 2 Tab, yakni **Indikator Kemiskinan** dan **Perbandingan Jumlah Penduduk Miskin**. 

Tingkat Kemiskinan di Kabupaten dalam Dashboard ini diukur melalui Rasio antara Penduduk Miskin dengan Total Penduduk. Rasio bernilai Tinggi (Jingga) jika Rasio penduduk miskin lebih dari 17%, Sedang (Biru) jika bernilai 13-17%, dan Rendah (Hijau) jika bernilai di bawah 13%.

**Dynamic Sliders:**  
```{r}


filter_slider("Mean_Harapan_Hidup", "Angka Harapan Hidup (Tahun)", sd_df, column=~Mean_Harapan_Hidup, step = 1)
filter_slider("Mean_Pengeluaran_PerKapita", "Pengeluaran per kapita Disesuaikan (ribu rupiah/orang/tahun)", sd_df, column=~Mean_Pengeluaran_PerKapita)


```


Row {data-height=550}
-------------------------------------

###

```{r}

    leaflet() %>%
    addTiles() %>%
    addAwesomeMarkers(data = sd_df, ~longitude, ~latitude, icon=icons, 
                      label=~as.character(kabupaten), layerId=~as.character(kabupaten), popup = ~as.character(Luas_Wilayah))
                              
                              
```

Row {data-height=450}
-------------------------------------

###

```{r}


d3scatter(sd_df, x = ~Mean_Pengeluaran_PerKapita, y = ~Mean_Harapan_Hidup, color = ~Kategori_Rasio,
          x_label = "Rataan Pengeluaran/Kapita", y_label = "Rataan Harapan Hidup")


```

###

```{r}


datatable(sd_df, rownames = FALSE, extensions = 'Scroller', 
          options = list(scrollY = 200, scroller = TRUE, columnDefs = list(list(className = 'dt-left', targets = 0:3))))



```

Perbandingan Jumlah Penduduk Miskin
=======================================================================

Row
-------------------------------------

### Peta Jawa Tengah

```{r}
output$map <- renderLeaflet({

  leaflet() %>%
    addTiles() %>%
    addAwesomeMarkers(data = lokasi_gis, ~longitude, ~latitude, icon=icons2, 
                      label=~as.character(kabupaten), layerId=~as.character(kabupaten), popup = ~as.character(Luas_Wilayah))

  
  
})

leafletOutput('map')
```

Row
-------------------------------------

### Berdasarkan Jumlah

```{r}

click_marker <- eventReactive(input$map_marker_click, {

  x <- input$map_marker_click
       return(x$id)
})

data_for_chart <- reactive({
  hasil4 <- hasil3[hasil$kabupaten == click_marker(),]
  return(hasil4)
})

output$chart <- renderHighchart({

  hasil4 <- hasil3[hasil3$kabupaten == click_marker(),]
  print(hasil4)
    hchart(hasil4, "column", hcaes(x = tahun, y = jumlah, group = keterangan))
})

highchartOutput('chart')

```

### Berdasarkan Persentase

```{r}
click_marker2 <- eventReactive(input$map_marker_click, {

  y <- input$map_marker_click
       return(y$id)
})

data_for_chart <- reactive({
  hasil6 <- hasil5[hasil$kabupaten == click_marker(),]
  return(hasil6)
})

output$chart2 <- renderHighchart({

  hasil6 <- hasil5[hasil5$kabupaten == click_marker(),]
  print(hasil6)
    hchart(hasil6, "line", hcaes(x = tahun, y = persentase, group = keterangan)) %>% 
      hc_yAxis(title = list(text = "Persentase Pertumbuhan"),
           labels = list(format = "{value}%")) %>% 
      hc_tooltip(pointFormat = "{point.y}%")
})

highchartOutput('chart2')
```